### ISSUE TITLE
Does not work for tabs within tab groups

### ISSUE THREAD

**Issue by kris-g** [sblask/webextension-open-tabs-next-to-current#103]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [ ] Firefox
- [x] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)
Does not work for tabs within tab groups. Tabs open to far right of the group.

**Comment by sblask** [comment]
I think there was an issue for that already, There is no API for tab groups, nothing that can be done here.
