### ISSUE TITLE
Microsoft Edge support

### ISSUE THREAD

**Issue by anewuser** [sblask/webextension-open-tabs-next-to-current#116]
This extension works on Microsoft Edge. You can submit it to https://microsoftedge.microsoft.com/

**Comment by sblask** [comment]
I know, but I won't do it, Firefox and Chrome web store are enough work already and as I don't use Edge...

**Comment by pbakes** [comment]
All chrome extensions work in Edge. Just go to the extension page by pasting it in Edge's address bar
