### ISSUE TITLE
new tab open on the left of the current one instead of right as usual 

### ISSUE THREAD

**Issue by thsecmaniac** [sblask/webextension-open-tabs-next-to-current#128]
### New Issue Checklist (tick off like this: `[x]`)

- [ ] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [ ] Firefox
- [ ] Chrome
- [x] Microsoft Edge

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Now, the extension open the new tab on the left of current one instead of right as usual

**Comment by sblask** [comment]
I don't use Edge, but I've seen problems on the latest Chrome release. Assuming it's the same problem, I think I've got a fix, will just do a bit more testing.

**Comment by sblask** [comment]
Pushed new version, should be fixed now.
