### ISSUE TITLE
A conflict with Tabs Outliner

### ISSUE THREAD

**Issue by artquest** [sblask/webextension-open-tabs-next-to-current#129]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [ ] Firefox
- [x] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Thank you for the extension.
The latest version conflicts with the Tabs Outliner extension (this is a tab/session manager). If you try to open a previously saved tab (b) (see the screen), which is a child of (a), and at the same time there's an open tab (c) below (b), and (c) is active, then (b) while being opened jumps down and opens below (c), and concurrently there is a "ghost" (b) in the old place, and this tab is "broken", when you try to activate it, new tabs open with an error. As a result, I have a broken tab hierarchy.
I assume that the reason for this behavior is the change in the method of moving a new tab to the currently open one. Can you please somehow adjust this move method so that it does not conflict with the Tabs Outliner, or please add an option to switch to the old method, because this problem did not occur on all previous versions.
I understand that solving this problem may be difficult, but maybe you'll like Tabs Outliner (for me it's an absolutely unique extension in its class) and you will want to fix the above error.

![tabs_outliner](https://user-images.githubusercontent.com/24230703/120377390-ba325880-c325-11eb-8097-b5983cb68d1d.png)

**Comment by sblask** [comment]
I don't see how my latest change could cause this kind of problem. If it worked before, it was probably by accident. How tabs are moved did not actually change, just the way the current tab is identified. There could be a problem in Tabs Outliner though caused by the latest Chrome version. I think in general you should probably not combine two extensions that are about tab positions. I am not interested in looking in Tabs Outliner.
