### ISSUE TITLE
Separate functionality for new tab button vs ctrl+t or right click + new tab

### ISSUE THREAD

**Issue by TheFaceCo** [sblask/webextension-open-tabs-next-to-current#165]
It would be awesome to have the new tab button in the tab bar behave normally, while all other New Tab options open next to the current tab. That would allow the option of expanding a pile of new tabs at the end of the line if desired.

### New Issue Checklist (tick off like this: `[x]`)

- [ ] I checked existing issues (open and closed) for possible duplicates
- [ ] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x ] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [ ] Windows

**Comment by sblask** [comment]
It's not possible.
