### ISSUE TITLE
Weird tab behavior

### ISSUE THREAD

**Issue by dingdingdon** [sblask/webextension-open-tabs-next-to-current#32]
The bug only appears after version 1.1.5,  this affects me using the imacro add on to create a new tab; I have to stay on version 1.1.5 to avoid the bug. I have recorded the action:

Setup: There are at least two tabs, and the current tab is on the left side or second last from the right.

The imacro code is:
```
TAB T=1
'open 2 tab
TAB OPEN
TAB OPEN

'go to tab 2
TAB T=2
'open google page
URL GOTO=www.google.com
TAB OPEN
TAB T=3
TAB T=1
```

The result should be google page next to the current select tab, the old version did the job, but after version 1.1.5, everything broke, the google tab becomes the 3rd, not the 2nd.

Should be work like this
https://www.screencast.com/t/CT8WKpiX

Newest version bug - Google tab page on the 3rd tab on the 2nd tab.
https://www.screencast.com/t/Qie7vgtk

**Comment by sblask** [comment]
The change between the version is using the new webextension API. If it doesn't work, there is nothing I can do about it. You can stick to the old version as long as it works (until Firefox 57). I don't know anything about Imacro, but if I understand the code correctly, the new behaviour is correct anyway: You have one tab, open 2 more in the background, go to tab 2 from the left and open Google - it should become the 3rd tab...

**Comment by dingdingdon** [comment]
The current open tab is TAB T=1 so the Google page should be on the second not the third, you can see the video record for the action The old version open the new tab next to current tab, but the webextention API open the next tab at the far right then move back next to the current tab, create this kind of issue. If I slow down the imacro speed, the issue was gone but my work requires your add on and imacro work very quickly.

There is nothing we can do to fix it?

**Comment by sblask** [comment]
Webextension event are asynchronous, so if it worked by slowing down things, it was just luck. It might work better when Imacro migrates to webextensions too. If it doesn't, it will stop anyway with Firefox 57...
