### ISSUE TITLE
Firefox note in Readme is out of date

### ISSUE THREAD

**Issue by autonome** [sblask/webextension-open-tabs-next-to-current#33]
insertRelatedAfterCurrent is the default now (for the last few versions IIRC?) so the note can be removed.

**Comment by sblask** [comment]
It's the default and that's why the note is still relevant. When you click `link1` and then `click2`, the default order of tabs will be `1` and `2`. If you disable `insertRelatedAfterCurrent`, it will be `2` and `1` (tabs are opened next to current).

**Comment by autonome** [comment]
Ahhhhh, that name is terrible! 😂
