### ISSUE TITLE
Potential hack to make the scrolling issue less jarring

### ISSUE THREAD

**Issue by hedning** [sblask/webextension-open-tabs-next-to-current#34]
Hi, here's a potential hack to make the scrolling, #26, a bit less jarring:

If you focus the originally focused tab before refocusing the newly opened tab, the original tab should stay visible at least. This also shouldn't mess with the optional most recently used `ctrl-tab` behavior either I think.

Focus would go like this, which should ensure that the original tab stays visible:

`origin tab` -> `new tab` (move it) -> `origin tab` -> `new tab`

Should be fairly easy to implement, just need some logic to determine if the new tab is opened in the background, in which case the refocus isn't necessary.

**Comment by sblask** [comment]
I've already considered this, I won't do it.
