### ISSUE TITLE
option to only put tabs opened by current tab to the right

### ISSUE THREAD

**Issue by chriszhxi** [sblask/webextension-open-tabs-next-to-current#38]
But still put new tab opened by click "+" and bookmark to the last.

**Comment by eduard93** [comment]
+1

**Comment by sblask** [comment]
You don't need this extension if you want this behaviour? Wouldn't the `browser.tabs.insertRelatedAfterCurrent` setting be enough?

**Comment by eduard93** [comment]
@sblask Thanks, that helped!
