### ISSUE TITLE
When a tab is opened from a pinned tab, the browser's focus does not move to the beginning of the tab list, stays at the end

### ISSUE THREAD

**Issue by DRSAgile** [sblask/webextension-open-tabs-next-to-current#39]
Thanks for the extension.

1. When a tab/link is opened from a pinned tab, the browser's focus does not move to the beginning of the tab list, where the tab is correctly opened, it stays at the end -- thus the user does not see the new tab as the focus is not there.

Normally it does not matter as few people use pinned tabs, but for those who do like myself it is an issue as every new opened tab/link requires additional clicks to actually see the tab.

If possible, can you please make sure that the extension keeps focus moved along with the newly opened tab?

2. Is it possible to assign double left click on mouse to create a new tab, not just the "+" icon in the UI?

Thank you in advance.

**Comment by sblask** [comment]
1: I could, but won't "fix" this because it would be super hacky playing around with focusing, which would probably result in even more movement in the tabbar (and people already complained that the tab is moved instead of appearing at the right spot)
2: not possible, there is no API for that
