### ISSUE TITLE
Incorrect information: "Firefox: Tabs that are opened by clicking on links are opened at the default location"

### ISSUE THREAD

**Issue by fireattack** [sblask/webextension-open-tabs-next-to-current#40]
Just tested in v57 stable and v59.0a1 (2017-11-14) (64-bit) Nightly.

Tabs opened by clicking links (child tabs) are still controlled by this add-on.

STR:

1) set `browser.tabs.insertRelatedAfterCurrent` to `false` (so child tabs will also open at the very right).
2) Install this add-on.

What expected: according to readme, it shouldn't change the behavior of child tab opening.
What observed: the behavior of child tab opening changed. It opens next to the parent tab.

**Comment by sblask** [comment]
The README is correct assuming `browser.tabs.insertRelatedAfterCurrent` is true by default? If it's true and you open A B C from tab X you get order X A B C. That's the default behaviour. If you follow the README "You can change the setting browser.tabs.insertRelatedAfterCurrent in about:config if you want even those to be opened right next to the current." The order is X C B A. That's the behaviour from this extension.

**Comment by fireattack** [comment]
Sorry, misunderstood that.

**Comment by fireattack** [comment]
Just tested again.

When `browser.tabs.insertRelatedAfterCurrent` is at default (true), it still opens as X C B A instead of default X A B C.

Can you double check?

Example:

![image](https://user-images.githubusercontent.com/4130991/32883413-f39fd070-ca7c-11e7-9257-a440a6c925ca.png)

**Comment by sblask** [comment]
The behaviour I described was due to a workaround that I could fix in #30 So you were right, the information if wrong and I'll fix it. Thanks for being persistent!

**Comment by fireattack** [comment]
Thanks! 

Is it possible to bring back "X A B C Y" behavior, though (as a feature request)? Or even not limited to links: if you open multiple new tabs (no matter how) in one-go, put them in sequence next to current.

**Comment by sblask** [comment]
See #38 ?

The multiple tabs behaviour is not a feature. I don't know of any way to fix it.

**Comment by d4k0** [comment]
I also wanted to suggest this ("X A B C Y" behavior) as a feature.

`rowser.tabs.insertRelatedAfterCurrent` only seems to work for single links. If you open a bookmark folder, all new tabs are created at the end of the tab list. With the add-on they are opened next to the current tab, but the order is "inverted" (and somehow the focus is on the first newly opened tab; I'm not sure if this is a bug).

So is there currently no way to influence the multiple tab behaviour?

**Comment by monk-time** [comment]
@d4k0, I agree with your suggestion, but just to note: `browser.tabs.insertRelatedAfterCurrent` is actually irrelevant here, the extension completely overrides and ignores it (as it should), but also breaks how Firefox (regardless of the setting) orders new tabs. See my comment in #36.

**Comment by sblask** [comment]
There is no way to influence the order for multiple tabs as they seem to get opened in batch and the events get fired in a batch too. It's not the same as opening tab after tab and the indexes are not right...
