### ISSUE TITLE
New tabs open one tab over from the current one (i.e. not next to it, but skips a tab)

### ISSUE THREAD

**Issue by LePhantomLimb** [sblask/webextension-open-tabs-next-to-current#42]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Just installed this.  When I open a new tab, it does not open next to the current tab, but rather, it opens next to the tab to the RIGHT of the current tab.  What I mean is, if the tabs are in order, A, B, C, D, and currently tab 'A' is open, the new tab will open between tab 'B' and 'C', rather than next to 'A'.  It doesn't matter if it's the first tab, or a tab in the middle that's open, the new tab will always skip one tab over to the right.  Of course if you're on the last tab, then this is a non-issue.  

I'm running the new Quantum Firefox now, so I don't know if this is an issue with the new Firefox or what, but I didn't see any open issues posted.

Let me know if I can provide more information.  Thanks.

**Comment by sblask** [comment]
Strange, I can't reproduce this at all and others don't seem to have this problem either. I am on Linux, but that shouldn't be the cause. I'd suspect a conflict with another extension. What else do you have installed?

**Comment by LePhantomLimb** [comment]
Seems you are correct.  I never would have thought (and I have no clue why) it is conflicting, but when I disable the "[New Tab Override](https://addons.mozilla.org/en-US/firefox/addon/new-tab-override/)" extension, then the problem stops.  

I am conflicted now... I used to use Tab Mix Plus (which doesn't work on this version of Firefox) which allowed me to both choose what site opened with new tabs, but also allowed new tabs to open next to the current tab... these are both features I want.  Anybody have any suggestions/solutions to this so I can run both extensions, or another extension that does both?

**Comment by sblask** [comment]
Sounds like an issue with New Tab Override. Not sure what business it has fiddling with tab order, I thought it just loads a new page into the tab.

**Comment by LePhantomLimb** [comment]
actually it's supposed to simply change *what* page is loaded when you load a new tab... no idea honestly why Firefox no longer allows you to choose

**Comment by sblask** [comment]
If you want to create an issue there, I think it's this bit of code: https://github.com/cadeyrn/newtaboverride/blob/70d2186b0eb7f8f5ddaaefb4f51b5332127f4ba2/src/js/core/newtab.js#L86

**Comment by lechner** [comment]
Hi, my new tabs skip one tab, as well. Did you submit this issue to [New Tab Override](https://github.com/cadeyrn/newtaboverride)? Thank you!

**Comment by sblask** [comment]
I didn't, feel free to do it.

**Comment by lechner** [comment]
Okay, I will. Would you share just one sentence as to why that is the offending line, please? Thank you!

**Comment by sblask** [comment]
I think it is a "race condition" between the two extensions. In the line, a tab is opened and another one immediately closed, my extension uses the index of the wrong one and can't do anything about it. From the sound of it, you might be able to configure something in the other extension, but I don't use it, so I can't help you there.

**Comment by lechner** [comment]
You found the bug! The line you identified is not run when the focus is set on the address bar in the other extension. Then the new tab opens next to the current one. Thank you!

**Comment by lechner** [comment]
You may also be interested in [this issue](https://github.com/cadeyrn/newtaboverride/issues/110) over there.

**Comment by LePhantomLimb** [comment]
Oh nice, so @lechner did you submit it then?  Does it sound like they might fix it?  I had given up and forgotten about the responses to this thread...

**Comment by lechner** [comment]
Haven't yet. It seemed they might implement "next-to-new" themselves...

**Comment by FengLengshun** [comment]
Hello, I have similar issue, in my case it happens whenever I re-open last closed tab. This seems to happen when I have recently opened a new tab, and then went and re-opened a previously closed one. It doesn't always happen, which is what makes replicating it hard, but in general, opening a bunch of new tabs in succession and switching tabs while doing so seems to confuse the extension, from my admittedly limited testing.

**Comment by sblask** [comment]
Webextension events are asynchronous, so anything can happen if you do too much in a short amount of time. Nothing that can be done about it.
