### ISSUE TITLE
Firefox : new tab opened on far right when duplicating tab 

### ISSUE THREAD

**Issue by piRGoif** [sblask/webextension-open-tabs-next-to-current#43]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Using Firefox 57.0 on Windows 7 with open tab next to current v2.0.10
When I right click on a tab and select duplicate, the new tab is opened on the far right, as all the tabs are before installing the extension.
Can the extension also handle this use case ?

**Comment by sblask** [comment]
I've got a fix, but it's weird. I think the problem got introduced when fixing #30. I expected duplicate tabs to be opened right next to the original, but never tested it. As you figured, it doesn't. Now the fix does to duplicated tabs, what it does to other tabs, moves them next to the current one. So when I duplicate the current tab, it does what I'd expect. But if I duplicate another tab, the new tab is still moved next to the current, not the original one. This feels weird, but there is nothing that I can do about it. Unless I introduce inconsistent behaviour. What do you think?

**Comment by piRGoif** [comment]
Thanks for your answer !
By current tab, I suppose you mean selected tab ?
I would understand if : you have 3 tabs A, B*, C (B* = selected tab), you duplicate A with a right click
=> result : A, B*, A', C.
But if I duplicate B I would expect to have A, B*, B', C
I this the behavior you're describing ?

**Comment by sblask** [comment]
Yes, this is what I meant and I think it's weird. I'd always expect a duplicated tab to end up next to the original. But if you think it's OK, I can just make the change. I am not using duplicate tab myself. Not even sure whether anybody even duplicates other tabs than the current one.

**Comment by piRGoif** [comment]
Totally agree !
And even if the behavior seems weird if it's documented as is it, well, users will say it is how it is ;)
Seriously indeed i agree with you, duplicating a tab certainly happens most of the time on the current/selected tab... And this fix would definitely improve the extension user experience !
