### ISSUE TITLE
Request: chosing the website linked in the new tab

### ISSUE THREAD

**Issue by LePhantomLimb** [sblask/webextension-open-tabs-next-to-current#44]
Not an issue, but I didn't know where else to post this.

Any chance you guys might be willing to add a feature that also allows the user to customize what website is opened when a new tab is selected?  Every add-on for this purpose conflicts with this extension for some reason.

Thanks, let me know!  :)

**Comment by sblask** [comment]
I think it would be much easier for the other extensions to include this extension's functionality than the other way around. I didn't look at their code in detail, but they must be doing something funny to break this extension//.
