### ISSUE TITLE
[Feature request] Don't scroll to the new tab in the tabbar

### ISSUE THREAD

**Issue by moontear** [sblask/webextension-open-tabs-next-to-current#46]
### New Issue Checklist

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description
If API limitation, don't mind this issue. Maybe as a reminder.

When opening a new tab with e.g. CTRL+T (or middle-mouse clicking) it gets opened next to the current one. It is annoying thought that the tab is also scrolled to in the tab bar, meaning this new tab is now the leftmost tab in the tab bar. Maybe this is because the tab is created in the last position and you just move it to the right of the previous tab?

It would be great if my initial position in the tab bar could be kept or remembered. Currently I loose track of "where I was" because the new tab changed the scroll position of my tab bar.

**Comment by sblask** [comment]
See closed issues, this has been discussed before.

**Comment by moontear** [comment]
Didn't see them in my initial search.
I'm assuming you mean #26, #24, #34 - https://bugzilla.mozilla.org/show_bug.cgi?id=1344749 also has relevant discussions relating to the API. Just linking here for future reference.

All very unfortunate, I would love the behavior of Tab Mix Plus back.
