### ISSUE TITLE
[Feature request] Don't reload all tabs from hidden container, if new tab created

### ISSUE THREAD

**Issue by moontear** [sblask/webextension-open-tabs-next-to-current#47]
### New Issue Checklist

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description
Consider a hidden container with 30 tabs (e.g. "Shopping"). Creating a new tab e.g. for Amazon (which is automatically "Shopping") this triggers making all of these 30 tabs visible, cluttering everything.

It would be great if not all tabs were repopulated upon adding a new tab that belongs to that group. I suppose that would make the option to hide/unhide single tabs per container necessary. This would allow for all tabs in a container to remain hidden, the new tab could be visible.

**Comment by sblask** [comment]
Hidden container? I have no idea what you are talking about.

**Comment by moontear** [comment]
On every container you have the possibility to "Hide this container" and to "Show this container" (on hidden containers).
Let's say the option "Hide this container" is activated for your "Shopping" container and you open a new Amazon tab which is automatically assigned the "Shopping" container - all other tabs that were previously hidden re-open now as well as soon as you open that Amazon tab.

**Comment by sblask** [comment]
I don't even know what containers are...

**Comment by moontear** [comment]
Uhm..... yeah.

Totally wrong repository, sorry Sebastian. Close/Delete this issue :)
