### ISSUE TITLE
[Feature Request] Use only on New Tabs and not when opening links into new tab

### ISSUE THREAD

**Issue by FengLengshun** [sblask/webextension-open-tabs-next-to-current#49]
### New Issue Checklist (tick off like this: `[x]`)

- [X] I checked existing issues (open and closed) for possible duplicates
- [X] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [X] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [X] Windows

### Description (please include examples/screenshots where applicable)

My primary need for this add-on is for opening a New Tab next to the current one, more than opening links in new tab in the newest-to-oldest order (I quite like Firefox's default behavior with opening links in new tabs you see). So I think it would be nice to have an option where it's enabled only for new tabs opened via the + sign or a keyboard shortcut.

Thanks in any case.

**Comment by sblask** [comment]
Special handling of `+` is not possible. Keyboard shortcut would be, but I don't really want to add an option which inverts the behaviour. I leave that up to a different extension.
