### ISSUE TITLE
Conflict

### ISSUE THREAD

**Issue by rayman89** [sblask/webextension-open-tabs-next-to-current#50]
On firefox 58 when using "New tab context" addon https://addons.mozilla.org/en-US/firefox/addon/new-tab-context/ opening a new tab using their function did open the new tab next to the tab that was right clicked but now (firefox 59) your addon forces the tab created by the addon to move next to the current tab. Is there a way your addon could respect the behavior of tabs opened by addons like it was pre 59?
Thank you.

**Comment by sblask** [comment]
I didn't change anything. Nothing I can do.

**Comment by rayman89** [comment]
Cant you give it a look to see if something is doable please?
