### ISSUE TITLE
Behaviour when middle-clicking items is wrong

### ISSUE THREAD

**Issue by Elronnd** [sblask/webextension-open-tabs-next-to-current#51]
### New Issue Checklist (tick off like this: `[x]`)

- [ ] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [x] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

So let's say my tab order currently looks like this: X Y and I'm currently on X.  With default FF, when I middle-click links A, B, and C (in that order) on X, my tab order is now X Y A B C.  Now, with this addon enabled, in waterfox I would get X A B C Y (the expected behaviour).  Now, however, in firefox, I instead get X C B A Y.  Because, I click A, and it opens right after X so X A Y.  Then I click on B and instead of opening after A, it opens, again, right after X, so X B A Y.  Same with C so X C B A Y.

**Comment by sblask** [comment]
X C B A Y is the expected behaviour, so it doesn't work under Waterfox.
