### ISSUE TITLE
Dragging links between two tabs does not open a new one between them

### ISSUE THREAD

**Issue by josemam** [sblask/webextension-open-tabs-next-to-current#54]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [x] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

When a link or text string is dragged between two tabs, a new tab is started next to the current one if the chosen gap is after the current tab or two positions after the current tab if the gap is before the current tab, overlooking the position where the link/string had been dropped. 
Tested in Firefox 58.0.2 64-bit in Windows and Firefox 58.0.2 32-bit in Ubuntu. Pretty sure it used to work as expected before Firefox Quantum.

**Comment by sblask** [comment]
Nothing that can be done about it.
