### ISSUE TITLE
Request: Open duplicated tabs next to original

### ISSUE THREAD

**Issue by syldub69** [sblask/webextension-open-tabs-next-to-current#55]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)
This is a potential duplicate with the issue #43 "Firefox : new tab opened on far right when duplicating tab"... actually I don't agree with what has been decided. I think you may introduce an option to control the behavior for the users who want a different behavior than the default one.

I'm using the "Open Tabs Next to Current" addon on On Firefox 58.0.2 64-bit.
If I right-click on a Tab which is not the current one, and if I select "Duplicate Tab", then the duplicated tab is opened next to the current one, and not next to the duplicated one. Which is strictly what the addon is meant to do... But the option to open the duplicated tab next to the duplicated one would be very interesting.
Tab Mix Plus had a specific setting for that : "Open duplicated tabs next to original"
The option would be great!!

**Comment by sblask** [comment]
See #43, it's rather edge case and there is no good way to do it. It would also only work for Firefox which will probably add a preference for where to open tabs in the near future leaving this add-on redundant.
