### ISSUE TITLE
Open multiple tabs next to current

### ISSUE THREAD

**Issue by orschiro** [sblask/webextension-open-tabs-next-to-current#56]
Hey @sblask,

Thanks so much for this great extension!

Just a minor request.

Can you support multiple tabs to open next to the current one?

Check this screencast: https://youtu.be/jTv5uQAR2ho

Thanks!

**Comment by sblask** [comment]
Sorry, it's not possible, no API available to get it done...

**Comment by orschiro** [comment]
What a bummer but thanks for your reply anyway!
