### ISSUE TITLE
Add support for "newTabPosition" API

### ISSUE THREAD

**Issue by Keith94** [sblask/webextension-open-tabs-next-to-current#58]
https://bugzilla.mozilla.org/show_bug.cgi?id=1344749 was fixed today; I'm wondering if this add-on should use the new API to control new tabs position.

>This patch implements the preference "browser.tabs.insertAfterCurrent" which,
when set to true, will cause all tabs (related and unrelated) to be opened next
to the current tab.

>It also implements the browserSettings API "newTabPosition", which allows
extensions to control both "browser.tabs.insertRelatedAfterCurrent", and
"browser.tabs.insertAfterCurrent" via values for "afterCurrent",
"relatedAfterCurrent" and "atEnd".

**Comment by sblask** [comment]
No, the new preference makes this extension obsolete. But thanks for keeping me updated on this.

**Comment by anewuser** [comment]
@sblask The new `browser.tabs.insertAfterCurrent` preference has been added to Firefox 61.0, released today.
