### ISSUE TITLE
Not working inside containers

### ISSUE THREAD

**Issue by Mikanoshi** [sblask/webextension-open-tabs-next-to-current#59]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Does not always work together with Conex (https://github.com/kesselborn/conex) when opening new tab (Ctrl+T), tab opens as last in a container most of the time and even out of the container.

**Comment by sblask** [comment]
Not exactly sure what that extension does, so nothing I can say about it...
