### ISSUE TITLE
Doesn't work with middle clicking links

### ISSUE THREAD

**Issue by Mr-Personality** [sblask/webextension-open-tabs-next-to-current#60]
This is a bug report/feature request.

I've just installed this and it works great when I press Ctrl+Shift T to open a new tab. But it doesn't work at all when I middle click links to open in a new window, which is the main reason I installed this add-on as I'm sick of links always opening at the very end of all the tabs.

I'm using Firefox 59.0.3 on Windows 7 x64

**Comment by sblask** [comment]
I just tried and it works for me. Only difference that I use Linux, but that shouldn't be a problem. So I suspect a conflict with a different extension and there is not much I can do about it.
