### ISSUE TITLE
FR: Option to switch hotkey and button behaviour

### ISSUE THREAD

**Issue by Boreeas** [sblask/webextension-open-tabs-next-to-current#61]
### New Issue Checklist 

- [X] I checked existing issues (open and closed) for possible duplicates

### What is your browser?

- [X] Firefox

### What is your operating system?

- [X] Windows

### Description (please include examples/screenshots where applicable)

My normal behaviour is that I usually want tabs to open at the end, and only occasionally need tabs next to the current one. It'd suit my workflow better if I could configure the hotkeys so that Ctrl+T retains its normal behaviour and Ctrl+Shift+Y is the new behaviour.

**Comment by sblask** [comment]
I want to keep this extension simple and not add options...
