### ISSUE TITLE
Control + click / middle click

### ISSUE THREAD

**Issue by rayman89** [sblask/webextension-open-tabs-next-to-current#62]
On the mailing list firefox has they said this

>When I open a tab, it will open on the farest right.

>     It won't if you middle (or ctrl/cmd-) click the new tab button,
>     it'll open a new tab immediately beside the current tab. I'm
>     pretty sure there are webextension add-ons that can make this the
>     default.

Can that be used somehow to open other tabs next to current without having to use the reposition method that you are currently using?

**Comment by sblask** [comment]
Nope. But you don't need this extension in Firefox anymore. I updated the README accordingly.

**Comment by rayman89** [comment]
I noticed that when using this on firefox tabs dont always open next to current. Tabs will use some kind of timer to determine in which proximity they should open. If you open it in succesion it will try to put the newest tab as the farthest from the related tabs that you just opened instead of the closest.

Example  C 5 4 3 2 1  instead of being C 1 2 3 4 5

C being current tab and 1 the first open tab (the oldest) from the succession of opened tabs and 5 being the newest tab (the last one opened).

Is there a way to solve this?

**Comment by sblask** [comment]
Isn't that what `browser.tabs.insertRelatedAfterCurrent` is for?

**Comment by rayman89** [comment]
Yeah at least now they are closer so it isn't as abrupt. I filed a bugzilla report to see if they do something about it. https://bugzilla.mozilla.org/show_bug.cgi?id=1485683
