### ISSUE TITLE
Tabs not keeping their position because of OTNTC

### ISSUE THREAD

**Issue by brain8891** [sblask/webextension-open-tabs-next-to-current#63]
https://support.mozilla.org/en-US/questions/1224534

There's now a built-in preference for this:

(1) In a new tab, type or paste about:config in the address bar and press Enter/Return. Click the button accepting the risk.

(2) In the search box above the list, type or paste insert and pause while the list is filtered

(3) Double-click the browser.tabs.insertAfterCurrent preference to switch the value from false to true 

### New Issue Checklist (tick off like this: `[x]`)

- [ x] I checked existing issues (open and closed) for possible duplicates
- [ x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x ] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x ] Windows

### Description (please include examples/screenshots where applicable)

1- when I am on a tab in a container then  use the middle click on the mouse to open a link next to the tab which opens in that container, I use [https://addons.mozilla.org/en-US/firefox/addon/context-plus/] to move the tab out of the container, but it moves it 1 tab further from the original  tab. When disabling Open Tabs Next to Current this issue disappears. 

2- another issue that I did not pin point to Open Tabs Next To Current, but it might be: Sometimes when I am on a website and middle click on a link the tabs open then disappears. It does not get hidden.

**Comment by sblask** [comment]
Probably a conflict with the other extension, but as you said, you can just use the new setting.
