### ISSUE TITLE
Request: New Tabs always open in default location

### ISSUE THREAD

**Issue by taelton** [sblask/webextension-open-tabs-next-to-current#64]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

I want new tabs to always open in the default location.  Can we get an option page to set that?  I know that Ctrl-Y (Ctrl-Shift-Y on Windows) can be used, but most people are conditioned to use Ctrl-T or click the button.

**Comment by sblask** [comment]
Won't do it because Ctrl-Y is a simple way to achieve this and everything else will add too much complexity.
