### ISSUE TITLE
messes up order when "Open all in tabs" from a bookmark folder is done.

### ISSUE THREAD

**Issue by lggjm** [sblask/webextension-open-tabs-next-to-current#65]
I'm using the plugin for Firefox on Windows 10. Everything works well, but when "open all in tabs" is done from a bookmarked folder, the tabs open in reverse order. I can confirm that it goes back to normal when the plugin is disabled. For example, if the bookmarks in the folder are Facebook, Twitter, Instagram, it should open in that order from left to right. With the plugin, "Open all in tabs" opens Instagram, Twitter, Facebook. Can this be fixed?

**Comment by sblask** [comment]
Can't be fixed, there is already a closed issue about this.
