### ISSUE TITLE
remove not needed anymore comment from Firefox extension page

### ISSUE THREAD

**Issue by Emilv2** [sblask/webextension-open-tabs-next-to-current#67]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [x] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)
On the Firefox add-on page is written

> "After the addition of the browser.tabs.insertAfterCurrent setting in about:config you do not need this extension anymore.

This is unfortunately not true, insertAfterCurrent only works for new tabs and not for links. This extension is still necessary if you want "open in new tab" links to be opened next to the current one.

**Comment by sblask** [comment]
Just checked and it works, even though it's not exactly the same behaviour. When I open links from a tab, the first one opens next to the current, the next one next to the first opened one. If I repeat the same after a while, it opens next to the current one again. So there is some magic timer. But it might be enough for some people. If it isn't, they can still use this extension...

**Comment by Emilv2** [comment]
I don't think there is a timer, I waited for more than an hour and it still shows the same behaviour. Switching tab seem to reset it.

And that is the same behaviour as before the `browser.tabs.insertAfterCurrent` I think. It's the same with the option on or off for me anyways. As I see it this option only changes the new tab function, but not the open in new tab function, for that you still need this extension.
