### ISSUE TITLE
Does not work together with Tree Style Tab

### ISSUE THREAD

**Issue by Emilv2** [sblask/webextension-open-tabs-next-to-current#68]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [x] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

Does not work together with https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/ . If Tree style tab is enabled, "open in new tab" has the default Firefox behaviour: tabs are opened right of other recently opened tabs instead of next to the current.

**Comment by sblask** [comment]
It looks like tree style tab moves an opened tab to that position(after this extension moved it next to the current one, which is the way it works). I don't think I can do something about it, but maybe you can make a feature request to tree style tabs to not move the tab?
