### ISSUE TITLE
New tabs always open to the right

### ISSUE THREAD

**Issue by brunobg** [sblask/webextension-open-tabs-next-to-current#69]
### New Issue Checklist (tick off like this: `[x]`)

- [X] I checked existing issues (open and closed) for possible duplicates
- [X] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [X] Firefox
- [ ] Chrome

### What is your operating system?

- [X] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

The plugin stopped working after I upgraded FF to 64.0.2. New tabs always open to the right.

**Comment by brunobg** [comment]
Actually this is explained by https://github.com/sblask/webextension-open-tabs-next-to-current/issues/67. Setting the config option fixed it. I suggest something more visible than the middle of the README in the plugin page, if possible a notification. Some plugins popup a new tab on upgrades. Closing this issue.

**Comment by sblask** [comment]
I just tried, it still works with version 64. The config option described in #67 does not come from this extension. But you can use it as an alternative.
