### ISSUE TITLE
[Feature request] Chrome: Default location when '+' is clicked

### ISSUE THREAD

**Issue by dannypernik** [sblask/webextension-open-tabs-next-to-current#70]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [ ] Firefox
- [x] Chrome

### What is your operating system?

- [ ] Linux
- [x] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

When I click the '+' at the far right of my tab list, it feels more intuitive for the tab to open right next to the '+'. However, I do prefer the new tab next to current when using Cmd+T. Would this be straightforward?

Also, you mention in the README that I need to set up the shortcuts "manually on the extension page in settings". However, I see no such option on the extension page. Am I missing something? Thank you for your work.

**Comment by sblask** [comment]
It's not possible to have special handling for the +.

There is a hamburger menu on the top left of the extension page. When you click on it, there is a link to the keyboard shortcuts.
