### ISSUE TITLE
"Undo closed tab" moved to wrong position

### ISSUE THREAD

**Issue by indivisible** [sblask/webextension-open-tabs-next-to-current#71]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [x] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Reopening closed tabs ("Undo Close Tab" or Ctrl+Shift+T), the tab will open as a completely new tab would, and is moved away from its restored position next to the currently focused tab.

The problem seems to be that it's never removed from `knownTabIDs`, so it will be treated like a duplicate.

 https://github.com/sblask/webextension-open-tabs-next-to-current/blob/ba8bddc4000f937597904626f34905f8365c8b8a/background.js#L88

**Comment by sblask** [comment]
No, I think the problem is https://github.com/sblask/webextension-open-tabs-next-to-current/blob/ba8bddc4000f937597904626f34905f8365c8b8a/background.js#L101

Firefox "uncloses" tabs at the end and not at the previous position and there is no way to detect that a tab has been "unclosed". "restored" in the code is about re-opening the browser and tabs being restored from the session.

**Comment by indivisible** [comment]
I've checked it in FF's debugger: the restored tab has the uuid tag the
acript sets, the tag is in the known set, and so it gets a new tag set and
is moved. If I don't let the script past that line (breakpoint) the tab
gets restored to its old position.

2019. jan. 30., Sze 16:31 dátummal Sebastian Blask <notifications@github.com>
ezt írta:

**Comment by sblask** [comment]
Ok, mixed it up with Chrome. However, just tried the following with Firefox 64:
 - open 10 tabs
 - focus tab 8
 - close tab 2
 - ctrl-shift-t
The closed tab is restored at position 2 and get the focus. Seems like the right behaviour to me? If there would be a bug, it should have been restored right next to tab 8?

**Comment by indivisible** [comment]
That sounds baffling. I've just tested what you describe on FF 64 and 65 and on both I see the tab recreated in the right position flickering to a position after the focused tab.

Did you try it with a fresh profile with only this extension installed from AMO?

**Comment by sblask** [comment]
Interesting, on a fresh profile I can reproduce it...

**Comment by ggoofer** [comment]
I also had this problem, but the extension is no longer needed: Mozilla added an entry `browser.tabs.insertAfterCurrent` in about config; switch to true. This fixes the problem for me.

Much thanks to developer for the add-on and the heads up about new method.

**Comment by sblask** [comment]
I think I fixed it by "forgetting" closed tabs as @indivisible suggested. Would you mind testing it with attached file? You'll have to load it temporarily under `about:debugging`

[open_tabs_next_to_current-2.0.12-firefox.zip](https://github.com/sblask/webextension-open-tabs-next-to-current/files/3124473/open_tabs_next_to_current-2.0.12-firefox.zip)

**Comment by indivisible** [comment]
I've just tested it with FF 66 and 60 (ESR). The bug looks fixed. Thanks for your work!
