### ISSUE TITLE
*Open Tabs Next to Current* is causing problems with *Tab Session Manager*

### ISSUE THREAD

**Issue by RobertAb1** [sblask/webextension-open-tabs-next-to-current#72]
@seniori (*Tab Session Manager* developer):
> The cause is probably that the tab specification of "Open Tabs Next to Current" is incorrect.
> Please use other add-on.
> https://addons.mozilla.org/ja/firefox/addon/always-right/

discussion/source: https://github.com/sienori/Tab-Session-Manager/issues/369

**Comment by sblask** [comment]
I have no idea what that means "the tab specification is incorrect"...

Seems to me like always-right uses this API: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings/newTabPosition which if I understand it correctly is the same as setting `browser.tabs.insertAfterCurrent` in about:config to true. So what's the point of having an extension for that at all? (see the README for this extension)

**Comment by RobertAb1** [comment]
I have just wanted to let you know that there is a problem with *Open Tabs Next to Current* running together with *Tab Session Manager*. The description of problems I experienced can be found here: https://github.com/sienori/Tab-Session-Manager/issues/369 (approx. Apr 6, 2019). I hope that this will help you find the reason why this is happening.

**Comment by sblask** [comment]
It's probably not a problem on my side, I have some special handling to avoid re-ordering for restored tabs. And that works well for tabs restored by Firefox directly. So I assume it the way tabs are restored by tab-session-manager.

**Comment by RobertAb1** [comment]
Maybe this will give you hint:
* *Open Tabs Next to Current* + Firefox Session Restore + no new tabs (empty tabs) => no issue
* *Open Tabs Next to Current* + Firefox Session Restore + new tabs (empty tabs) => no issue
* *Open Tabs Next to Current* + *Tab Session Manager* + no new tabs (empty tabs) => no issue
* *Open Tabs Next to Current* + *Tab Session Manager* + new tabs (empty tabs) => **issue**

I have problem with order of tabs in Firefox window only in the last case, when both extensions are present and there are new tab (empty tabs) present. 
Please, check  sienori/Tab-Session-Manager#369 (approx. Apr 6, 2019) for details.
