### ISSUE TITLE
[Question] open tab next to current before the webextension migration (for firefox esr 52)

### ISSUE THREAD

**Issue by sebma** [sblask/webextension-open-tabs-next-to-current#73]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [x] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

Hi, I'm looking for a previous release of your addon, the one before the webextension migration.

Can you please share this old release so I can download and install it ?

Thank you for your comprehension.

**Comment by sblask** [comment]
You can possibly go through the commit history and find the point before the migration. Not sure what you will find and if you can get it to work. I have no time to check.
