### ISSUE TITLE
Always open new tab page and bookmarks as last tab

### ISSUE THREAD

**Issue by DimkaDim** [sblask/webextension-open-tabs-next-to-current#74]
I like it when middle-clicked links open after active tab. But with this extension, all kinds of newly created tabs open after active tab as well, even when they are unrelated to it. It disrupts grouping of related tabs.

If you have time, please, make middle-clicked bookmarks and new tab page opened by "+" button (and Chrome's other internal pages) open as last tab always. Tab Mix Plus in old Firefox allowed setup like this and it was perfect.

I'm almost certain that this is doable with extensions API:
1) Any internal service page (including new tab page) of Chrome can be determined by matching tab's address with mask 
`chrome://*`
For example, "chrome://newtab"

I can already achieve this behavior with extension "Tab Position Options":
![2019-06-29_13-33-48](https://user-images.githubusercontent.com/43080384/60382931-12de8400-9a73-11e9-9a9d-aa6b93e4d78a.png)

2) To determine whether new tab's address is bookmarked, there is a method in extensions API that searches for string in user's bookmarks. It's not a perfect solution, but if there are no better ones, it'll do the trick.

**Comment by sblask** [comment]
I am not interested in implementing this, but if you want, you can do it. Please re-open in this case.
