### ISSUE TITLE
Open links from desktop notifications in the end of tabs

### ISSUE THREAD

**Issue by vstepaniuk** [sblask/webextension-open-tabs-next-to-current#75]
### New Issue Checklist (tick off like this: `[x]`)

- [x ] I checked existing issues (open and closed) for possible duplicates
- [x ] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x ] Firefox
- [ ] Chrome

### What is your operating system?

- [x ] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

I am using Feedbro ([https://addons.mozilla.org/en-US/firefox/addon/feedbroreader](https://addons.mozilla.org/en-US/firefox/addon/feedbroreader/)) to get the RSS desktop notifications. When I click on the notification it opens a link in a new tab. Is it possible to keep opening these links in the end of tabs?

**Comment by sblask** [comment]
Not sure why, but I missed this issue. I don't think there is a way to tell whether a link was opened from from a desktop notification and I have no time to investigate this further. If someone does, please re-open.
