### ISSUE TITLE
Facebook container tab opens not next to current, but far right

### ISSUE THREAD

**Issue by arlavit** [sblask/webextension-open-tabs-next-to-current#76]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)
When I open facebook container tab, the tab moves right and stays there, so it doesn't open next to a current one.

**Comment by sblask** [comment]
Not sure why, but I missed this issue. I don't use containers at all, so I am not sure how they look like but the problem sounds like they might get grouped so the position I get from the API is off. No time to look into this, but if there is anybody who wants to look into it, please re-open.
