### ISSUE TITLE
Can we have an option to tabs next to pinned tabs on the left-most of the current screen?

### ISSUE THREAD

**Issue by levihb** [sblask/webextension-open-tabs-next-to-current#80]
### New Issue Checklist (tick off like this: `[x]`)

- [X] I checked existing issues (open and closed) for possible duplicates
- [X] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [X] Firefox
- [ ] Chrome

### What is your operating system?

- [X] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)

If I use a pinned tab, then any links I open from there currently open in the very left-most of the tab list. This is rather annoying as if I'm scrolled to tab 289 out of 539 for example, then open a new tab from a pinned one, it will jump me all the way back to the start. I like to have tons of tabs open, which originally brought me to this addon (as otherwise it's a pain, e.g. having to open a new link then change it).

So having the ability to open a new tab to the left of the currently scrolled screen would be great.

**Comment by sblask** [comment]
Not possible, information on where you are currently scrolled at is not available in the API
