### ISSUE TITLE
Doesn't support Chrome group

### ISSUE THREAD

**Issue by c02y** [sblask/webextension-open-tabs-next-to-current#85]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [ ] Firefox
- [x] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)
Recent Chrome introduced new feature called group, I noticed that this extension doesn't support for group, which means, when I open a new tab inside a group, new tab will be added at the end of the current group of tabs instead of next to the current tab.

NOTE: Here the new tab means open a bookmark in new tab, not the situation that use Ctrl-t to create an empty new tab, Ctrl-t still works well with this extension.

And I notice that the latest version was released in 2017, is it in maintenance status?

**Comment by sblask** [comment]
Works for me? What exactly are you trying to do? How do you open the bookmark?

I on my side have problems opening tabs from another tab because Chrome started to do its own grouping (not tab groups) instead of opening new tabs at the end.

There hasn't been anything to add to this extension since 2017...

**Comment by c02y** [comment]
There is a bookmark bar, I click a bookmark in it, open it in new tab, it is opened in the end of the group instead of next to the current tab.

**Comment by sblask** [comment]
I know now what's happening and there is nothing I can do without breaking something else. When opening a tab from the bookmark bar it is usually opened at the end of the tabstrip. When in a tab group, it's opened at the end of the group. But I have no idea that the current tab is in a group (there is no information in the API), all I have is the index. The index makes the new tab appear as if it got re-opened after closing and re-opened tabs are not moved but end up in their original position.
