### ISSUE TITLE
Release notes at AMO

### ISSUE THREAD

**Issue by grahamperrin** [sblask/webextension-open-tabs-next-to-current#94]
Can you publish release notes at AMO? For the notes to be seen in Firefox: 

![image](https://user-images.githubusercontent.com/192271/90521642-b355a300-e162-11ea-9ee5-3b73aa51f164.png)

Thanks

**Comment by sblask** [comment]
Nothing really changed for Firefox in a long time, the recent update was only to have the same version for Firefox and Chrome.

**Comment by sblask** [comment]
But if you can recommend tools for generating release notes, I might look into them for feature releases or my other extensions.
